// Expo config plugin: build the Android app entirely with Java 21.
//
// React Native 0.85's Gradle plugin (JdkConfiguratorUtils) hard-pins every
// module to Java 17 -- both `source/targetCompatibility = 17` and the Kotlin
// `jvmToolchain(17)`. The toolchain pin means a JDK 17 must be installed even
// when Gradle itself runs on a newer JDK. This plugin:
//
//   1. Sets `react.internal.disableJavaVersionAlignment=true`, which makes RNGP
//      skip its Java-17 alignment for all modules.
//   2. Re-aligns every Android/Kotlin module to Java 21 in the root
//      build.gradle. Because Gradle runs on JDK 21, `jvmToolchain(21)` resolves
//      to the running JDK -- no JDK 17 is needed anywhere.
//
// `android/` is gitignored and regenerated by `expo prebuild`, so these edits
// live here (a config plugin) rather than in the generated Gradle files.

const {
  withGradleProperties,
  withProjectBuildGradle,
  withAppBuildGradle,
} = require("@expo/config-plugins");

const JAVA_VERSION = "21";

const APP_MARKER = "// withJava21: app module compileOptions";
const appCompileOptions = `    ${APP_MARKER}
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_${JAVA_VERSION}
        targetCompatibility JavaVersion.VERSION_${JAVA_VERSION}
    }`;

const ALIGN_START = "// >>> withJava21 alignment >>>";
const ALIGN_END = "// <<< withJava21 alignment <<<";

const alignBlock = `${ALIGN_START}
// Re-align every module to Java ${JAVA_VERSION}, replacing React Native's
// disabled Java-17 alignment (see plugins/withJava21.js). Mirrors RN's own
// JdkConfiguratorUtils: set Java via AndroidComponents.finalizeDsl (right
// phase to win over AGP's 1.8 default) and Kotlin via jvmTarget.
allprojects { subproject ->
  subproject.plugins.withId("com.android.application") {
    subproject.extensions
      .getByType(com.android.build.api.variant.ApplicationAndroidComponentsExtension)
      .finalizeDsl { ext ->
        ext.compileOptions.sourceCompatibility = JavaVersion.VERSION_${JAVA_VERSION}
        ext.compileOptions.targetCompatibility = JavaVersion.VERSION_${JAVA_VERSION}
      }
  }
  subproject.plugins.withId("com.android.library") {
    subproject.extensions
      .getByType(com.android.build.api.variant.LibraryAndroidComponentsExtension)
      .finalizeDsl { ext ->
        ext.compileOptions.sourceCompatibility = JavaVersion.VERSION_${JAVA_VERSION}
        ext.compileOptions.targetCompatibility = JavaVersion.VERSION_${JAVA_VERSION}
      }
  }
  subproject.plugins.withId("org.jetbrains.kotlin.android") {
    subproject.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      kotlinOptions { jvmTarget = "${JAVA_VERSION}" }
    }
  }
}
${ALIGN_END}`;

function withDisableRnJavaAlignment(config) {
  return withGradleProperties(config, (config) => {
    const key = "react.internal.disableJavaVersionAlignment";
    const existing = config.modResults.find(
      (item) => item.type === "property" && item.key === key,
    );
    if (existing) {
      existing.value = "true";
    } else {
      config.modResults.push({ type: "property", key, value: "true" });
    }
    return config;
  });
}

function withJava21Alignment(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error(
        "withJava21: expected the root build.gradle to be Groovy.",
      );
    }
    let contents = config.modResults.contents;
    const startIdx = contents.indexOf(ALIGN_START);
    if (startIdx !== -1) {
      // Idempotent: replace any previously injected block.
      const endIdx = contents.indexOf(ALIGN_END, startIdx);
      const sliceEnd = endIdx === -1 ? contents.length : endIdx + ALIGN_END.length;
      contents = contents.slice(0, startIdx) + alignBlock + contents.slice(sliceEnd);
    } else {
      contents = contents.trimEnd() + "\n\n" + alignBlock + "\n";
    }
    config.modResults.contents = contents;
    return config;
  });
}

function withAppModuleJava21(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error(
        "withJava21: expected the app build.gradle to be Groovy.",
      );
    }
    let contents = config.modResults.contents;
    if (contents.includes(APP_MARKER)) {
      return config; // already injected
    }
    // Insert compileOptions just inside the `android {` block.
    const anchor = contents.match(/\nandroid\s*\{[^\n]*\n/);
    if (!anchor) {
      throw new Error("withJava21: could not find the `android {` block in app build.gradle.");
    }
    const insertAt = anchor.index + anchor[0].length;
    contents = contents.slice(0, insertAt) + appCompileOptions + "\n" + contents.slice(insertAt);
    config.modResults.contents = contents;
    return config;
  });
}

module.exports = function withJava21(config) {
  config = withDisableRnJavaAlignment(config);
  config = withJava21Alignment(config);
  config = withAppModuleJava21(config);
  return config;
};
